//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace org.jiechan.service.cn.org.renzhe.u.shopx3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ShopX3Soap", Namespace="http://x4.renzhe.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelPick[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class ShopX3 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllPickModulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadClassStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClassStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback doitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ShopX3() {
            this.Url = global::org.jiechan.service.Properties.Settings.Default.org_renzhe_plat_service_cn_org_renzhe_u_shopx3_ShopX3;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllPickModulesCompletedEventHandler GetAllPickModulesCompleted;
        
        /// <remarks/>
        public event UploadClassStrCompletedEventHandler UploadClassStrCompleted;
        
        /// <remarks/>
        public event GetClassStrCompletedEventHandler GetClassStrCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event ReNameCompletedEventHandler ReNameCompleted;
        
        /// <remarks/>
        public event doitCompletedEventHandler doitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x4.renzhe.org/GetAllPickModules", RequestNamespace="http://x4.renzhe.org/", ResponseNamespace="http://x4.renzhe.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ModelPick[] GetAllPickModules() {
            object[] results = this.Invoke("GetAllPickModules", new object[0]);
            return ((ModelPick[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPickModulesAsync() {
            this.GetAllPickModulesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPickModulesAsync(object userState) {
            if ((this.GetAllPickModulesOperationCompleted == null)) {
                this.GetAllPickModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPickModulesOperationCompleted);
            }
            this.InvokeAsync("GetAllPickModules", new object[0], this.GetAllPickModulesOperationCompleted, userState);
        }
        
        private void OnGetAllPickModulesOperationCompleted(object arg) {
            if ((this.GetAllPickModulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPickModulesCompleted(this, new GetAllPickModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x4.renzhe.org/UploadClassStr", RequestNamespace="http://x4.renzhe.org/", ResponseNamespace="http://x4.renzhe.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadClassStr(string fileName, string fileClassStr, mType mtype) {
            object[] results = this.Invoke("UploadClassStr", new object[] {
                        fileName,
                        fileClassStr,
                        mtype});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadClassStrAsync(string fileName, string fileClassStr, mType mtype) {
            this.UploadClassStrAsync(fileName, fileClassStr, mtype, null);
        }
        
        /// <remarks/>
        public void UploadClassStrAsync(string fileName, string fileClassStr, mType mtype, object userState) {
            if ((this.UploadClassStrOperationCompleted == null)) {
                this.UploadClassStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadClassStrOperationCompleted);
            }
            this.InvokeAsync("UploadClassStr", new object[] {
                        fileName,
                        fileClassStr,
                        mtype}, this.UploadClassStrOperationCompleted, userState);
        }
        
        private void OnUploadClassStrOperationCompleted(object arg) {
            if ((this.UploadClassStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadClassStrCompleted(this, new UploadClassStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x4.renzhe.org/GetClassStr", RequestNamespace="http://x4.renzhe.org/", ResponseNamespace="http://x4.renzhe.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetClassStr(string fileName, mType mtype) {
            object[] results = this.Invoke("GetClassStr", new object[] {
                        fileName,
                        mtype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetClassStrAsync(string fileName, mType mtype) {
            this.GetClassStrAsync(fileName, mtype, null);
        }
        
        /// <remarks/>
        public void GetClassStrAsync(string fileName, mType mtype, object userState) {
            if ((this.GetClassStrOperationCompleted == null)) {
                this.GetClassStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassStrOperationCompleted);
            }
            this.InvokeAsync("GetClassStr", new object[] {
                        fileName,
                        mtype}, this.GetClassStrOperationCompleted, userState);
        }
        
        private void OnGetClassStrOperationCompleted(object arg) {
            if ((this.GetClassStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClassStrCompleted(this, new GetClassStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x4.renzhe.org/Delete", RequestNamespace="http://x4.renzhe.org/", ResponseNamespace="http://x4.renzhe.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete(string classMemberObj, string fileName, mType mtype) {
            object[] results = this.Invoke("Delete", new object[] {
                        classMemberObj,
                        fileName,
                        mtype});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string classMemberObj, string fileName, mType mtype) {
            this.DeleteAsync(classMemberObj, fileName, mtype, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string classMemberObj, string fileName, mType mtype, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        classMemberObj,
                        fileName,
                        mtype}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x4.renzhe.org/ReName", RequestNamespace="http://x4.renzhe.org/", ResponseNamespace="http://x4.renzhe.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ReName(string classMemberObj, string fileName, string fileNewName, mType mtype) {
            object[] results = this.Invoke("ReName", new object[] {
                        classMemberObj,
                        fileName,
                        fileNewName,
                        mtype});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReNameAsync(string classMemberObj, string fileName, string fileNewName, mType mtype) {
            this.ReNameAsync(classMemberObj, fileName, fileNewName, mtype, null);
        }
        
        /// <remarks/>
        public void ReNameAsync(string classMemberObj, string fileName, string fileNewName, mType mtype, object userState) {
            if ((this.ReNameOperationCompleted == null)) {
                this.ReNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReNameOperationCompleted);
            }
            this.InvokeAsync("ReName", new object[] {
                        classMemberObj,
                        fileName,
                        fileNewName,
                        mtype}, this.ReNameOperationCompleted, userState);
        }
        
        private void OnReNameOperationCompleted(object arg) {
            if ((this.ReNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReNameCompleted(this, new ReNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x4.renzhe.org/doit", RequestNamespace="http://x4.renzhe.org/", ResponseNamespace="http://x4.renzhe.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void doit() {
            this.Invoke("doit", new object[0]);
        }
        
        /// <remarks/>
        public void doitAsync() {
            this.doitAsync(null);
        }
        
        /// <remarks/>
        public void doitAsync(object userState) {
            if ((this.doitOperationCompleted == null)) {
                this.doitOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoitOperationCompleted);
            }
            this.InvokeAsync("doit", new object[0], this.doitOperationCompleted, userState);
        }
        
        private void OndoitOperationCompleted(object arg) {
            if ((this.doitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x4.renzhe.org/")]
    public partial class ModelPick {
        
        private string pickNameField;
        
        private string fullNameField;
        
        private string modelPassWordField;
        
        private string modelAuthorField;
        
        private string modelEmailField;
        
        private string modelQQField;
        
        private string modelUrlField;
        
        private string modelDescriptionField;
        
        private bool isPubField;
        
        private bool isFanZhuaQuField;
        
        private long fileSizeField;
        
        private System.DateTime lastUpDateField;
        
        private string indexUrlStrField;
        
        private bool isZhizhuField;
        
        private string urlhasField;
        
        private string urlNotHasField;
        
        private string linCookiesField;
        
        private int pageIncrField;
        
        private string currentConUrlField;
        
        private int intervalTimeField;
        
        private bool isAutoModelGetField;
        
        private int minLengthField;
        
        private string titleRegexField;
        
        private string title2RegexField;
        
        private string contentRegexsField;
        
        private string summaryField;
        
        private string htmlAliasField;
        
        private string tagsRegxField;
        
        private string keyWordRegexField;
        
        private string putTimeRegField;
        
        private string authorRegexField;
        
        private string comeFromRegexField;
        
        private string comeFromUrlRegexField;
        
        private string clickNumRegexField;
        
        private string artPassWordRegexField;
        
        private string isReplyField;
        
        private string isQuoteField;
        
        private string quartUrlsField;
        
        private bool noimgField;
        
        private bool no2brField;
        
        private bool isAutoNextPageField;
        
        private string strReplaceField;
        
        private string zdy01Field;
        
        private string zdy02Field;
        
        private string zdy03Field;
        
        private string zdy04Field;
        
        private string zdy05Field;
        
        private string zdy06Field;
        
        private string zdy07Field;
        
        private string zdy08Field;
        
        private string zdy09Field;
        
        private string zdy10Field;
        
        private string zdy11Field;
        
        private string zdy12Field;
        
        private string zdy13Field;
        
        private string zdy14Field;
        
        private string zdy15Field;
        
        private string zdy16Field;
        
        private string zdy17Field;
        
        private string zdy18Field;
        
        private string zdy19Field;
        
        private string zdy20Field;
        
        private object[] indexUrlsField;
        
        private object[] listUrlField;
        
        private bool isMoreField;
        
        private string string1Field;
        
        private string string2Field;
        
        private string string3Field;
        
        private string string4Field;
        
        private string string5Field;
        
        private string string6Field;
        
        private string string7Field;
        
        private string string8Field;
        
        private string string9Field;
        
        private string string10Field;
        
        private string string11Field;
        
        private string string12Field;
        
        private string string13Field;
        
        private string string14Field;
        
        private string string15Field;
        
        private string string16Field;
        
        private string string17Field;
        
        private string string18Field;
        
        private string string19Field;
        
        private string string20Field;
        
        private int int1Field;
        
        private int int2Field;
        
        private int int3Field;
        
        private int int4Field;
        
        private int int5Field;
        
        private int int6Field;
        
        private int int7Field;
        
        private int int8Field;
        
        private int int9Field;
        
        private System.DateTime dateTime1Field;
        
        private System.DateTime dateTime2Field;
        
        private System.DateTime dateTime3Field;
        
        private System.DateTime dateTime4Field;
        
        private System.DateTime dateTime5Field;
        
        private System.DateTime dateTime6Field;
        
        private System.DateTime dateTime7Field;
        
        private System.DateTime dateTime8Field;
        
        private System.DateTime dateTime9Field;
        
        /// <remarks/>
        public string PickName {
            get {
                return this.pickNameField;
            }
            set {
                this.pickNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string ModelPassWord {
            get {
                return this.modelPassWordField;
            }
            set {
                this.modelPassWordField = value;
            }
        }
        
        /// <remarks/>
        public string ModelAuthor {
            get {
                return this.modelAuthorField;
            }
            set {
                this.modelAuthorField = value;
            }
        }
        
        /// <remarks/>
        public string ModelEmail {
            get {
                return this.modelEmailField;
            }
            set {
                this.modelEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ModelQQ {
            get {
                return this.modelQQField;
            }
            set {
                this.modelQQField = value;
            }
        }
        
        /// <remarks/>
        public string ModelUrl {
            get {
                return this.modelUrlField;
            }
            set {
                this.modelUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ModelDescription {
            get {
                return this.modelDescriptionField;
            }
            set {
                this.modelDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPub {
            get {
                return this.isPubField;
            }
            set {
                this.isPubField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFanZhuaQu {
            get {
                return this.isFanZhuaQuField;
            }
            set {
                this.isFanZhuaQuField = value;
            }
        }
        
        /// <remarks/>
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpDate {
            get {
                return this.lastUpDateField;
            }
            set {
                this.lastUpDateField = value;
            }
        }
        
        /// <remarks/>
        public string IndexUrlStr {
            get {
                return this.indexUrlStrField;
            }
            set {
                this.indexUrlStrField = value;
            }
        }
        
        /// <remarks/>
        public bool IsZhizhu {
            get {
                return this.isZhizhuField;
            }
            set {
                this.isZhizhuField = value;
            }
        }
        
        /// <remarks/>
        public string Urlhas {
            get {
                return this.urlhasField;
            }
            set {
                this.urlhasField = value;
            }
        }
        
        /// <remarks/>
        public string UrlNotHas {
            get {
                return this.urlNotHasField;
            }
            set {
                this.urlNotHasField = value;
            }
        }
        
        /// <remarks/>
        public string linCookies {
            get {
                return this.linCookiesField;
            }
            set {
                this.linCookiesField = value;
            }
        }
        
        /// <remarks/>
        public int PageIncr {
            get {
                return this.pageIncrField;
            }
            set {
                this.pageIncrField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentConUrl {
            get {
                return this.currentConUrlField;
            }
            set {
                this.currentConUrlField = value;
            }
        }
        
        /// <remarks/>
        public int IntervalTime {
            get {
                return this.intervalTimeField;
            }
            set {
                this.intervalTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAutoModelGet {
            get {
                return this.isAutoModelGetField;
            }
            set {
                this.isAutoModelGetField = value;
            }
        }
        
        /// <remarks/>
        public int MinLength {
            get {
                return this.minLengthField;
            }
            set {
                this.minLengthField = value;
            }
        }
        
        /// <remarks/>
        public string TitleRegex {
            get {
                return this.titleRegexField;
            }
            set {
                this.titleRegexField = value;
            }
        }
        
        /// <remarks/>
        public string Title2Regex {
            get {
                return this.title2RegexField;
            }
            set {
                this.title2RegexField = value;
            }
        }
        
        /// <remarks/>
        public string ContentRegexs {
            get {
                return this.contentRegexsField;
            }
            set {
                this.contentRegexsField = value;
            }
        }
        
        /// <remarks/>
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        public string HtmlAlias {
            get {
                return this.htmlAliasField;
            }
            set {
                this.htmlAliasField = value;
            }
        }
        
        /// <remarks/>
        public string TagsRegx {
            get {
                return this.tagsRegxField;
            }
            set {
                this.tagsRegxField = value;
            }
        }
        
        /// <remarks/>
        public string KeyWordRegex {
            get {
                return this.keyWordRegexField;
            }
            set {
                this.keyWordRegexField = value;
            }
        }
        
        /// <remarks/>
        public string PutTimeReg {
            get {
                return this.putTimeRegField;
            }
            set {
                this.putTimeRegField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorRegex {
            get {
                return this.authorRegexField;
            }
            set {
                this.authorRegexField = value;
            }
        }
        
        /// <remarks/>
        public string ComeFromRegex {
            get {
                return this.comeFromRegexField;
            }
            set {
                this.comeFromRegexField = value;
            }
        }
        
        /// <remarks/>
        public string ComeFromUrlRegex {
            get {
                return this.comeFromUrlRegexField;
            }
            set {
                this.comeFromUrlRegexField = value;
            }
        }
        
        /// <remarks/>
        public string ClickNumRegex {
            get {
                return this.clickNumRegexField;
            }
            set {
                this.clickNumRegexField = value;
            }
        }
        
        /// <remarks/>
        public string ArtPassWordRegex {
            get {
                return this.artPassWordRegexField;
            }
            set {
                this.artPassWordRegexField = value;
            }
        }
        
        /// <remarks/>
        public string IsReply {
            get {
                return this.isReplyField;
            }
            set {
                this.isReplyField = value;
            }
        }
        
        /// <remarks/>
        public string IsQuote {
            get {
                return this.isQuoteField;
            }
            set {
                this.isQuoteField = value;
            }
        }
        
        /// <remarks/>
        public string QuartUrls {
            get {
                return this.quartUrlsField;
            }
            set {
                this.quartUrlsField = value;
            }
        }
        
        /// <remarks/>
        public bool Noimg {
            get {
                return this.noimgField;
            }
            set {
                this.noimgField = value;
            }
        }
        
        /// <remarks/>
        public bool No2br {
            get {
                return this.no2brField;
            }
            set {
                this.no2brField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAutoNextPage {
            get {
                return this.isAutoNextPageField;
            }
            set {
                this.isAutoNextPageField = value;
            }
        }
        
        /// <remarks/>
        public string StrReplace {
            get {
                return this.strReplaceField;
            }
            set {
                this.strReplaceField = value;
            }
        }
        
        /// <remarks/>
        public string zdy01 {
            get {
                return this.zdy01Field;
            }
            set {
                this.zdy01Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy02 {
            get {
                return this.zdy02Field;
            }
            set {
                this.zdy02Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy03 {
            get {
                return this.zdy03Field;
            }
            set {
                this.zdy03Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy04 {
            get {
                return this.zdy04Field;
            }
            set {
                this.zdy04Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy05 {
            get {
                return this.zdy05Field;
            }
            set {
                this.zdy05Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy06 {
            get {
                return this.zdy06Field;
            }
            set {
                this.zdy06Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy07 {
            get {
                return this.zdy07Field;
            }
            set {
                this.zdy07Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy08 {
            get {
                return this.zdy08Field;
            }
            set {
                this.zdy08Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy09 {
            get {
                return this.zdy09Field;
            }
            set {
                this.zdy09Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy10 {
            get {
                return this.zdy10Field;
            }
            set {
                this.zdy10Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy11 {
            get {
                return this.zdy11Field;
            }
            set {
                this.zdy11Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy12 {
            get {
                return this.zdy12Field;
            }
            set {
                this.zdy12Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy13 {
            get {
                return this.zdy13Field;
            }
            set {
                this.zdy13Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy14 {
            get {
                return this.zdy14Field;
            }
            set {
                this.zdy14Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy15 {
            get {
                return this.zdy15Field;
            }
            set {
                this.zdy15Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy16 {
            get {
                return this.zdy16Field;
            }
            set {
                this.zdy16Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy17 {
            get {
                return this.zdy17Field;
            }
            set {
                this.zdy17Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy18 {
            get {
                return this.zdy18Field;
            }
            set {
                this.zdy18Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy19 {
            get {
                return this.zdy19Field;
            }
            set {
                this.zdy19Field = value;
            }
        }
        
        /// <remarks/>
        public string zdy20 {
            get {
                return this.zdy20Field;
            }
            set {
                this.zdy20Field = value;
            }
        }
        
        /// <remarks/>
        public object[] IndexUrls {
            get {
                return this.indexUrlsField;
            }
            set {
                this.indexUrlsField = value;
            }
        }
        
        /// <remarks/>
        public object[] ListUrl {
            get {
                return this.listUrlField;
            }
            set {
                this.listUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMore {
            get {
                return this.isMoreField;
            }
            set {
                this.isMoreField = value;
            }
        }
        
        /// <remarks/>
        public string string1 {
            get {
                return this.string1Field;
            }
            set {
                this.string1Field = value;
            }
        }
        
        /// <remarks/>
        public string string2 {
            get {
                return this.string2Field;
            }
            set {
                this.string2Field = value;
            }
        }
        
        /// <remarks/>
        public string string3 {
            get {
                return this.string3Field;
            }
            set {
                this.string3Field = value;
            }
        }
        
        /// <remarks/>
        public string string4 {
            get {
                return this.string4Field;
            }
            set {
                this.string4Field = value;
            }
        }
        
        /// <remarks/>
        public string string5 {
            get {
                return this.string5Field;
            }
            set {
                this.string5Field = value;
            }
        }
        
        /// <remarks/>
        public string string6 {
            get {
                return this.string6Field;
            }
            set {
                this.string6Field = value;
            }
        }
        
        /// <remarks/>
        public string string7 {
            get {
                return this.string7Field;
            }
            set {
                this.string7Field = value;
            }
        }
        
        /// <remarks/>
        public string string8 {
            get {
                return this.string8Field;
            }
            set {
                this.string8Field = value;
            }
        }
        
        /// <remarks/>
        public string string9 {
            get {
                return this.string9Field;
            }
            set {
                this.string9Field = value;
            }
        }
        
        /// <remarks/>
        public string string10 {
            get {
                return this.string10Field;
            }
            set {
                this.string10Field = value;
            }
        }
        
        /// <remarks/>
        public string string11 {
            get {
                return this.string11Field;
            }
            set {
                this.string11Field = value;
            }
        }
        
        /// <remarks/>
        public string string12 {
            get {
                return this.string12Field;
            }
            set {
                this.string12Field = value;
            }
        }
        
        /// <remarks/>
        public string string13 {
            get {
                return this.string13Field;
            }
            set {
                this.string13Field = value;
            }
        }
        
        /// <remarks/>
        public string string14 {
            get {
                return this.string14Field;
            }
            set {
                this.string14Field = value;
            }
        }
        
        /// <remarks/>
        public string string15 {
            get {
                return this.string15Field;
            }
            set {
                this.string15Field = value;
            }
        }
        
        /// <remarks/>
        public string string16 {
            get {
                return this.string16Field;
            }
            set {
                this.string16Field = value;
            }
        }
        
        /// <remarks/>
        public string string17 {
            get {
                return this.string17Field;
            }
            set {
                this.string17Field = value;
            }
        }
        
        /// <remarks/>
        public string string18 {
            get {
                return this.string18Field;
            }
            set {
                this.string18Field = value;
            }
        }
        
        /// <remarks/>
        public string string19 {
            get {
                return this.string19Field;
            }
            set {
                this.string19Field = value;
            }
        }
        
        /// <remarks/>
        public string string20 {
            get {
                return this.string20Field;
            }
            set {
                this.string20Field = value;
            }
        }
        
        /// <remarks/>
        public int int1 {
            get {
                return this.int1Field;
            }
            set {
                this.int1Field = value;
            }
        }
        
        /// <remarks/>
        public int int2 {
            get {
                return this.int2Field;
            }
            set {
                this.int2Field = value;
            }
        }
        
        /// <remarks/>
        public int int3 {
            get {
                return this.int3Field;
            }
            set {
                this.int3Field = value;
            }
        }
        
        /// <remarks/>
        public int int4 {
            get {
                return this.int4Field;
            }
            set {
                this.int4Field = value;
            }
        }
        
        /// <remarks/>
        public int int5 {
            get {
                return this.int5Field;
            }
            set {
                this.int5Field = value;
            }
        }
        
        /// <remarks/>
        public int int6 {
            get {
                return this.int6Field;
            }
            set {
                this.int6Field = value;
            }
        }
        
        /// <remarks/>
        public int int7 {
            get {
                return this.int7Field;
            }
            set {
                this.int7Field = value;
            }
        }
        
        /// <remarks/>
        public int int8 {
            get {
                return this.int8Field;
            }
            set {
                this.int8Field = value;
            }
        }
        
        /// <remarks/>
        public int int9 {
            get {
                return this.int9Field;
            }
            set {
                this.int9Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime1 {
            get {
                return this.dateTime1Field;
            }
            set {
                this.dateTime1Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime2 {
            get {
                return this.dateTime2Field;
            }
            set {
                this.dateTime2Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime3 {
            get {
                return this.dateTime3Field;
            }
            set {
                this.dateTime3Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime4 {
            get {
                return this.dateTime4Field;
            }
            set {
                this.dateTime4Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime5 {
            get {
                return this.dateTime5Field;
            }
            set {
                this.dateTime5Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime6 {
            get {
                return this.dateTime6Field;
            }
            set {
                this.dateTime6Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime7 {
            get {
                return this.dateTime7Field;
            }
            set {
                this.dateTime7Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime8 {
            get {
                return this.dateTime8Field;
            }
            set {
                this.dateTime8Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime9 {
            get {
                return this.dateTime9Field;
            }
            set {
                this.dateTime9Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x4.renzhe.org/")]
    public enum mType {
        
        /// <remarks/>
        抓取模块,
        
        /// <remarks/>
        个人数据,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllPickModulesCompletedEventHandler(object sender, GetAllPickModulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPickModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPickModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ModelPick[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ModelPick[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadClassStrCompletedEventHandler(object sender, UploadClassStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadClassStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadClassStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClassStrCompletedEventHandler(object sender, GetClassStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClassStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClassStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReNameCompletedEventHandler(object sender, ReNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void doitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591